### ISSUE TITLE
Ask: Should admin backend reside in this repo or separate repo?

### ISSUE THREAD

**Issue by supasate** [youpin-city/youpin-web#15]
@rapee

**Comment by rapee** [comment]
Should be on a new repo i.e. `youpin-city/youpin-backend`

**Comment by supasate** [comment]
What about `youpin-city/youpin-web-admin`? Just wanna make it clear that it's not the backend tech stack.

**Comment by rapee** [comment]
Ok

**Comment by supasate** [comment]
Done. https://github.com/youpin-city/youpin-web-admin

cc. @heytitle @tvirot @puripant @parnurzeal
